name: Generate Contribution Wave

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Contribution Wave
        uses: Platane/snk@master   # Snake & Wave generator
        with:
          github_user_name: sanjayram-07
          outputs: |
            dist/contribution-wave.svg

      - name: Push Contribution Wave
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
